FROM node:22-alpine AS base
WORKDIR /app

FROM base AS deps
COPY package.json package-lock.json* ./
COPY apps/cms/package.json ./apps/cms/
RUN npm install --workspace=@radio-seneca/cms

FROM base AS runner
ENV NODE_ENV=production
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY package.json ./
COPY apps/cms ./apps/cms
WORKDIR /app/apps/cms
RUN npm run build
EXPOSE 1337
CMD ["npm", "run", "start"]
